# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92ccdbca72b659d0ca00ec631ae07d4ee60a0c1f64e3989b8a588de0a0777ea44e68c6a4658841f5ffe38c067bd42c3bc7571c8a1785ba4847cc628e6a2c291e

test:
  secret_key_base: 00ccf04c43858aa31f0631ea1386af4f059aec74e8c0005e69f5f9985ecd5aa4d967a86e9d8e979eeb20938d5c13ab8a0dcc1ecc47eafa7d98ba7e6fbdd0156e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
